-- CreateEnum
CREATE TYPE "JobType" AS ENUM ('COMPANY_RESEARCH', 'CONTACT_DISCOVERY', 'OUTREACH_GENERATION', 'EMAIL_DISPATCH', 'SCHEDULED_FOLLOW_UP_CHECK', 'WEBHOOK_PROCESSING');

UPDATE "jobs" SET "type" = 'COMPANY_RESEARCH' WHERE "type" = 'RESEARCH_COMPANY';
UPDATE "jobs" SET "type" = 'OUTREACH_GENERATION' WHERE "type" = 'GENERATE_OUTREACH';
UPDATE "jobs" SET "type" = 'EMAIL_DISPATCH' WHERE "type" = 'SEND_EMAIL';

-- AlterTable
ALTER TABLE "jobs" ALTER COLUMN "type" TYPE "JobType" USING "type"::text::"JobType";
