packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.13'
  - '@turbo/darwin-arm64@2.10.13'
  - '@turbo/linux-64@2.10.13'
  - '@turbo/linux-arm64@2.10.13'
  - '@turbo/windows-64@2.10.13'
  - '@turbo/windows-arm64@2.10.13'
  - turbo@2.10.13
