/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCampaignsRouteImport } from './routes/_authed/campaigns'
import { Route as AuthedCompaniesRouteImport } from './routes/_authed/companies'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTemplatesRouteImport } from './routes/_authed/templates'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsRoute = AuthedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompaniesRoute = AuthedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTemplatesRoute = AuthedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/campaigns': typeof AuthedCampaignsRoute
  '/companies': typeof AuthedCompaniesRoute
  '/settings': typeof AuthedSettingsRoute
  '/templates': typeof AuthedTemplatesRoute
  '/login': typeof GuestLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/campaigns': typeof AuthedCampaignsRoute
  '/companies': typeof AuthedCompaniesRoute
  '/settings': typeof AuthedSettingsRoute
  '/templates': typeof AuthedTemplatesRoute
  '/login': typeof GuestLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authed/campaigns': typeof AuthedCampaignsRoute
  '/_authed/companies': typeof AuthedCompaniesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/templates': typeof AuthedTemplatesRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/campaigns' | '/companies' | '/settings' | '/templates' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campaigns' | '/companies' | '/settings' | '/templates' | '/login'
  id:
    | '__root__'
    | '/_authed'
    | '/_guest'
    | '/_authed/campaigns'
    | '/_authed/companies'
    | '/_authed/settings'
    | '/_authed/templates'
    | '/_guest/login'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campaigns': {
      id: '/_authed/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthedCampaignsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/companies': {
      id: '/_authed/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthedCompaniesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/templates': {
      id: '/_authed/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthedTemplatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCampaignsRoute: typeof AuthedCampaignsRoute
  AuthedCompaniesRoute: typeof AuthedCompaniesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTemplatesRoute: typeof AuthedTemplatesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCampaignsRoute: AuthedCampaignsRoute,
  AuthedCompaniesRoute: AuthedCompaniesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTemplatesRoute: AuthedTemplatesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
