/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthedCampaignsRouteImport } from './routes/_authed/campaigns'
import { Route as AuthedContactsRouteImport } from './routes/_authed/contacts'
import { Route as AuthedConversationsRouteImport } from './routes/_authed/conversations'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedOpportunitiesRouteImport } from './routes/_authed/opportunities'
import { Route as AuthedOutreachesRouteImport } from './routes/_authed/outreaches'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTemplatesRouteImport } from './routes/_authed/templates'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as AuthedCampaignsIndexRouteImport } from './routes/_authed/campaigns.index'
import { Route as AuthedCompaniesIndexRouteImport } from './routes/_authed/companies.index'
import { Route as AuthedCompaniesIdRouteImport } from './routes/_authed/companies.$id'
import { Route as AuthedContactsIndexRouteImport } from './routes/_authed/contacts.index'
import { Route as AuthedConversationsIndexRouteImport } from './routes/_authed/conversations.index'
import { Route as AuthedOpportunitiesIndexRouteImport } from './routes/_authed/opportunities.index'
import { Route as AuthedOutreachesIndexRouteImport } from './routes/_authed/outreaches.index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsCareerProfileRouteImport } from './routes/_authed/settings/career-profile'
import { Route as AuthedSettingsIntegrationsRouteImport } from './routes/_authed/settings/integrations'
import { Route as AuthedSettingsSendersRouteImport } from './routes/_authed/settings/senders'
import { Route as AuthedCampaignsCampaignIdReviewRouteImport } from './routes/_authed/campaigns.$campaignId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCampaignsRoute = AuthedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContactsRoute = AuthedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConversationsRoute = AuthedConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOpportunitiesRoute = AuthedOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOutreachesRoute = AuthedOutreachesRouteImport.update({
  id: '/outreaches',
  path: '/outreaches',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTemplatesRoute = AuthedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRoute,
} as any)
const AuthedCampaignsIndexRoute = AuthedCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCampaignsRoute,
} as any)
const AuthedCompaniesIndexRoute = AuthedCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompaniesIdRoute = AuthedCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContactsIndexRoute = AuthedContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedContactsRoute,
} as any)
const AuthedConversationsIndexRoute =
  AuthedConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedConversationsRoute,
  } as any)
const AuthedOpportunitiesIndexRoute =
  AuthedOpportunitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOpportunitiesRoute,
  } as any)
const AuthedOutreachesIndexRoute = AuthedOutreachesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOutreachesRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsCareerProfileRoute =
  AuthedSettingsCareerProfileRouteImport.update({
    id: '/career-profile',
    path: '/career-profile',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsIntegrationsRoute =
  AuthedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsSendersRoute = AuthedSettingsSendersRouteImport.update({
  id: '/senders',
  path: '/senders',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedCampaignsCampaignIdReviewRoute =
  AuthedCampaignsCampaignIdReviewRouteImport.update({
    id: '/$campaignId/review',
    path: '/$campaignId/review',
    getParentRoute: () => AuthedCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns': typeof AuthedCampaignsRouteWithChildren
  '/contacts': typeof AuthedContactsRouteWithChildren
  '/conversations': typeof AuthedConversationsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/opportunities': typeof AuthedOpportunitiesRouteWithChildren
  '/outreaches': typeof AuthedOutreachesRouteWithChildren
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/templates': typeof AuthedTemplatesRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/companies/$id': typeof AuthedCompaniesIdRoute
  '/settings/career-profile': typeof AuthedSettingsCareerProfileRoute
  '/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/settings/senders': typeof AuthedSettingsSendersRoute
  '/campaigns/': typeof AuthedCampaignsIndexRoute
  '/companies/': typeof AuthedCompaniesIndexRoute
  '/contacts/': typeof AuthedContactsIndexRoute
  '/conversations/': typeof AuthedConversationsIndexRoute
  '/opportunities/': typeof AuthedOpportunitiesIndexRoute
  '/outreaches/': typeof AuthedOutreachesIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/campaigns/$campaignId/review': typeof AuthedCampaignsCampaignIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/templates': typeof AuthedTemplatesRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/companies/$id': typeof AuthedCompaniesIdRoute
  '/settings/career-profile': typeof AuthedSettingsCareerProfileRoute
  '/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/settings/senders': typeof AuthedSettingsSendersRoute
  '/campaigns': typeof AuthedCampaignsIndexRoute
  '/companies': typeof AuthedCompaniesIndexRoute
  '/contacts': typeof AuthedContactsIndexRoute
  '/conversations': typeof AuthedConversationsIndexRoute
  '/opportunities': typeof AuthedOpportunitiesIndexRoute
  '/outreaches': typeof AuthedOutreachesIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/campaigns/$campaignId/review': typeof AuthedCampaignsCampaignIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authed/campaigns': typeof AuthedCampaignsRouteWithChildren
  '/_authed/contacts': typeof AuthedContactsRouteWithChildren
  '/_authed/conversations': typeof AuthedConversationsRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/opportunities': typeof AuthedOpportunitiesRouteWithChildren
  '/_authed/outreaches': typeof AuthedOutreachesRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/templates': typeof AuthedTemplatesRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_authed/companies/$id': typeof AuthedCompaniesIdRoute
  '/_authed/settings/career-profile': typeof AuthedSettingsCareerProfileRoute
  '/_authed/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/_authed/settings/senders': typeof AuthedSettingsSendersRoute
  '/_authed/campaigns/': typeof AuthedCampaignsIndexRoute
  '/_authed/companies/': typeof AuthedCompaniesIndexRoute
  '/_authed/contacts/': typeof AuthedContactsIndexRoute
  '/_authed/conversations/': typeof AuthedConversationsIndexRoute
  '/_authed/opportunities/': typeof AuthedOpportunitiesIndexRoute
  '/_authed/outreaches/': typeof AuthedOutreachesIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/campaigns/$campaignId/review': typeof AuthedCampaignsCampaignIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/campaigns'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/opportunities'
    | '/outreaches'
    | '/settings'
    | '/templates'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/companies/$id'
    | '/settings/career-profile'
    | '/settings/integrations'
    | '/settings/senders'
    | '/campaigns/'
    | '/companies/'
    | '/contacts/'
    | '/conversations/'
    | '/opportunities/'
    | '/outreaches/'
    | '/settings/'
    | '/campaigns/$campaignId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/templates'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/companies/$id'
    | '/settings/career-profile'
    | '/settings/integrations'
    | '/settings/senders'
    | '/campaigns'
    | '/companies'
    | '/contacts'
    | '/conversations'
    | '/opportunities'
    | '/outreaches'
    | '/settings'
    | '/campaigns/$campaignId/review'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_guest'
    | '/onboarding'
    | '/_authed/campaigns'
    | '/_authed/contacts'
    | '/_authed/conversations'
    | '/_authed/dashboard'
    | '/_authed/opportunities'
    | '/_authed/outreaches'
    | '/_authed/settings'
    | '/_authed/templates'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_authed/companies/$id'
    | '/_authed/settings/career-profile'
    | '/_authed/settings/integrations'
    | '/_authed/settings/senders'
    | '/_authed/campaigns/'
    | '/_authed/companies/'
    | '/_authed/contacts/'
    | '/_authed/conversations/'
    | '/_authed/opportunities/'
    | '/_authed/outreaches/'
    | '/_authed/settings/'
    | '/_authed/campaigns/$campaignId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/campaigns': {
      id: '/_authed/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthedCampaignsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contacts': {
      id: '/_authed/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthedContactsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/conversations': {
      id: '/_authed/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthedConversationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/opportunities': {
      id: '/_authed/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthedOpportunitiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/outreaches': {
      id: '/_authed/outreaches'
      path: '/outreaches'
      fullPath: '/outreaches'
      preLoaderRoute: typeof AuthedOutreachesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/templates': {
      id: '/_authed/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthedTemplatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authed/campaigns/': {
      id: '/_authed/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthedCampaignsIndexRouteImport
      parentRoute: typeof AuthedCampaignsRoute
    }
    '/_authed/companies/': {
      id: '/_authed/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthedCompaniesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/companies/$id': {
      id: '/_authed/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthedCompaniesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contacts/': {
      id: '/_authed/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthedContactsIndexRouteImport
      parentRoute: typeof AuthedContactsRoute
    }
    '/_authed/conversations/': {
      id: '/_authed/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthedConversationsIndexRouteImport
      parentRoute: typeof AuthedConversationsRoute
    }
    '/_authed/opportunities/': {
      id: '/_authed/opportunities/'
      path: '/'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AuthedOpportunitiesIndexRouteImport
      parentRoute: typeof AuthedOpportunitiesRoute
    }
    '/_authed/outreaches/': {
      id: '/_authed/outreaches/'
      path: '/'
      fullPath: '/outreaches/'
      preLoaderRoute: typeof AuthedOutreachesIndexRouteImport
      parentRoute: typeof AuthedOutreachesRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/career-profile': {
      id: '/_authed/settings/career-profile'
      path: '/career-profile'
      fullPath: '/settings/career-profile'
      preLoaderRoute: typeof AuthedSettingsCareerProfileRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/integrations': {
      id: '/_authed/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/senders': {
      id: '/_authed/settings/senders'
      path: '/senders'
      fullPath: '/settings/senders'
      preLoaderRoute: typeof AuthedSettingsSendersRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/campaigns/$campaignId/review': {
      id: '/_authed/campaigns/$campaignId/review'
      path: '/$campaignId/review'
      fullPath: '/campaigns/$campaignId/review'
      preLoaderRoute: typeof AuthedCampaignsCampaignIdReviewRouteImport
      parentRoute: typeof AuthedCampaignsRoute
    }
  }
}

interface AuthedCampaignsRouteChildren {
  AuthedCampaignsIndexRoute: typeof AuthedCampaignsIndexRoute
  AuthedCampaignsCampaignIdReviewRoute: typeof AuthedCampaignsCampaignIdReviewRoute
}

const AuthedCampaignsRouteChildren: AuthedCampaignsRouteChildren = {
  AuthedCampaignsIndexRoute: AuthedCampaignsIndexRoute,
  AuthedCampaignsCampaignIdReviewRoute: AuthedCampaignsCampaignIdReviewRoute,
}

const AuthedCampaignsRouteWithChildren = AuthedCampaignsRoute._addFileChildren(
  AuthedCampaignsRouteChildren,
)

interface AuthedContactsRouteChildren {
  AuthedContactsIndexRoute: typeof AuthedContactsIndexRoute
}

const AuthedContactsRouteChildren: AuthedContactsRouteChildren = {
  AuthedContactsIndexRoute: AuthedContactsIndexRoute,
}

const AuthedContactsRouteWithChildren = AuthedContactsRoute._addFileChildren(
  AuthedContactsRouteChildren,
)

interface AuthedConversationsRouteChildren {
  AuthedConversationsIndexRoute: typeof AuthedConversationsIndexRoute
}

const AuthedConversationsRouteChildren: AuthedConversationsRouteChildren = {
  AuthedConversationsIndexRoute: AuthedConversationsIndexRoute,
}

const AuthedConversationsRouteWithChildren =
  AuthedConversationsRoute._addFileChildren(AuthedConversationsRouteChildren)

interface AuthedOpportunitiesRouteChildren {
  AuthedOpportunitiesIndexRoute: typeof AuthedOpportunitiesIndexRoute
}

const AuthedOpportunitiesRouteChildren: AuthedOpportunitiesRouteChildren = {
  AuthedOpportunitiesIndexRoute: AuthedOpportunitiesIndexRoute,
}

const AuthedOpportunitiesRouteWithChildren =
  AuthedOpportunitiesRoute._addFileChildren(AuthedOpportunitiesRouteChildren)

interface AuthedOutreachesRouteChildren {
  AuthedOutreachesIndexRoute: typeof AuthedOutreachesIndexRoute
}

const AuthedOutreachesRouteChildren: AuthedOutreachesRouteChildren = {
  AuthedOutreachesIndexRoute: AuthedOutreachesIndexRoute,
}

const AuthedOutreachesRouteWithChildren =
  AuthedOutreachesRoute._addFileChildren(AuthedOutreachesRouteChildren)

interface AuthedSettingsRouteChildren {
  AuthedSettingsCareerProfileRoute: typeof AuthedSettingsCareerProfileRoute
  AuthedSettingsIntegrationsRoute: typeof AuthedSettingsIntegrationsRoute
  AuthedSettingsSendersRoute: typeof AuthedSettingsSendersRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsCareerProfileRoute: AuthedSettingsCareerProfileRoute,
  AuthedSettingsIntegrationsRoute: AuthedSettingsIntegrationsRoute,
  AuthedSettingsSendersRoute: AuthedSettingsSendersRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCampaignsRoute: typeof AuthedCampaignsRouteWithChildren
  AuthedContactsRoute: typeof AuthedContactsRouteWithChildren
  AuthedConversationsRoute: typeof AuthedConversationsRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedOpportunitiesRoute: typeof AuthedOpportunitiesRouteWithChildren
  AuthedOutreachesRoute: typeof AuthedOutreachesRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedTemplatesRoute: typeof AuthedTemplatesRoute
  AuthedCompaniesIdRoute: typeof AuthedCompaniesIdRoute
  AuthedCompaniesIndexRoute: typeof AuthedCompaniesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCampaignsRoute: AuthedCampaignsRouteWithChildren,
  AuthedContactsRoute: AuthedContactsRouteWithChildren,
  AuthedConversationsRoute: AuthedConversationsRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedOpportunitiesRoute: AuthedOpportunitiesRouteWithChildren,
  AuthedOutreachesRoute: AuthedOutreachesRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedTemplatesRoute: AuthedTemplatesRoute,
  AuthedCompaniesIdRoute: AuthedCompaniesIdRoute,
  AuthedCompaniesIndexRoute: AuthedCompaniesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
