/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCampaignsRouteImport } from './routes/_authed/campaigns'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTemplatesRouteImport } from './routes/_authed/templates'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthedCampaignsIndexRouteImport } from './routes/_authed/campaigns.index'
import { Route as AuthedCompaniesIndexRouteImport } from './routes/_authed/companies.index'
import { Route as AuthedCompaniesIdRouteImport } from './routes/_authed/companies.$id'
import { Route as AuthedCampaignsCampaignIdReviewRouteImport } from './routes/_authed/campaigns.$campaignId.review'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsRoute = AuthedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTemplatesRoute = AuthedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthedCampaignsIndexRoute = AuthedCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCampaignsRoute,
} as any)
const AuthedCompaniesIndexRoute = AuthedCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompaniesIdRoute = AuthedCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsCampaignIdReviewRoute =
  AuthedCampaignsCampaignIdReviewRouteImport.update({
    id: '/$campaignId/review',
    path: '/$campaignId/review',
    getParentRoute: () => AuthedCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/campaigns': typeof AuthedCampaignsRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/templates': typeof AuthedTemplatesRoute
  '/login': typeof GuestLoginRoute
  '/companies/$id': typeof AuthedCompaniesIdRoute
  '/campaigns/': typeof AuthedCampaignsIndexRoute
  '/companies/': typeof AuthedCompaniesIndexRoute
  '/campaigns/$campaignId/review': typeof AuthedCampaignsCampaignIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/settings': typeof AuthedSettingsRoute
  '/templates': typeof AuthedTemplatesRoute
  '/login': typeof GuestLoginRoute
  '/companies/$id': typeof AuthedCompaniesIdRoute
  '/campaigns': typeof AuthedCampaignsIndexRoute
  '/companies': typeof AuthedCompaniesIndexRoute
  '/campaigns/$campaignId/review': typeof AuthedCampaignsCampaignIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authed/campaigns': typeof AuthedCampaignsRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/templates': typeof AuthedTemplatesRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/companies/$id': typeof AuthedCompaniesIdRoute
  '/_authed/campaigns/': typeof AuthedCampaignsIndexRoute
  '/_authed/companies/': typeof AuthedCompaniesIndexRoute
  '/_authed/campaigns/$campaignId/review': typeof AuthedCampaignsCampaignIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/settings'
    | '/templates'
    | '/login'
    | '/companies/$id'
    | '/campaigns/'
    | '/companies/'
    | '/campaigns/$campaignId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/templates'
    | '/login'
    | '/companies/$id'
    | '/campaigns'
    | '/companies'
    | '/campaigns/$campaignId/review'
  id:
    | '__root__'
    | '/_authed'
    | '/_guest'
    | '/_authed/campaigns'
    | '/_authed/settings'
    | '/_authed/templates'
    | '/_guest/login'
    | '/_authed/'
    | '/_authed/companies/$id'
    | '/_authed/campaigns/'
    | '/_authed/companies/'
    | '/_authed/campaigns/$campaignId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campaigns': {
      id: '/_authed/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthedCampaignsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/templates': {
      id: '/_authed/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthedTemplatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authed/campaigns/': {
      id: '/_authed/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthedCampaignsIndexRouteImport
      parentRoute: typeof AuthedCampaignsRoute
    }
    '/_authed/companies/': {
      id: '/_authed/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthedCompaniesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/companies/$id': {
      id: '/_authed/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthedCompaniesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/campaigns/$campaignId/review': {
      id: '/_authed/campaigns/$campaignId/review'
      path: '/$campaignId/review'
      fullPath: '/campaigns/$campaignId/review'
      preLoaderRoute: typeof AuthedCampaignsCampaignIdReviewRouteImport
      parentRoute: typeof AuthedCampaignsRoute
    }
  }
}

interface AuthedCampaignsRouteChildren {
  AuthedCampaignsIndexRoute: typeof AuthedCampaignsIndexRoute
  AuthedCampaignsCampaignIdReviewRoute: typeof AuthedCampaignsCampaignIdReviewRoute
}

const AuthedCampaignsRouteChildren: AuthedCampaignsRouteChildren = {
  AuthedCampaignsIndexRoute: AuthedCampaignsIndexRoute,
  AuthedCampaignsCampaignIdReviewRoute: AuthedCampaignsCampaignIdReviewRoute,
}

const AuthedCampaignsRouteWithChildren = AuthedCampaignsRoute._addFileChildren(
  AuthedCampaignsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCampaignsRoute: typeof AuthedCampaignsRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTemplatesRoute: typeof AuthedTemplatesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCompaniesIdRoute: typeof AuthedCompaniesIdRoute
  AuthedCompaniesIndexRoute: typeof AuthedCompaniesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCampaignsRoute: AuthedCampaignsRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTemplatesRoute: AuthedTemplatesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCompaniesIdRoute: AuthedCompaniesIdRoute,
  AuthedCompaniesIndexRoute: AuthedCompaniesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
