export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PROVIDER_FAILURE: 'PROVIDER_FAILURE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  COMPANY_DUPLICATE_NAME: 'COMPANY_DUPLICATE_NAME',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
